# Generated by Django 5.1.1 on 2024-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_date', models.DateField()),
                ('names_owners', models.CharField(max_length=64)),
                ('email_owners', models.EmailField(max_length=128)),
                ('count_money', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('currency_money', models.CharField(max_length=2)),
            ],
        ),
    ]
